### ISSUE TITLE
Safari broken

### ISSUE THREAD

**Issue by exomarty** [NodeBB/nodebb-plugin-composer-redactor#4] opened 2015-07-28 13:01 UTC
Cant write text on safari browser, mac & iOS

**Comment by mrgame64** [comment] 2015-08-01 12:10
I'm unable to reproduce the problem on Safari in OSX 10.10, it works just fine

**Comment by exomarty** [comment] 2015-08-01 12:44
Mmm, maybe a theme issue then. wich theme you tried?

**Comment by mrgame64** [comment] 2015-08-01 12:47
I'm using Persona

**Comment by tfraley** [comment] 2015-08-01 22:42
I'm noticing the same thing. Cannot type in safari but works fine in chrome..
I'm using the material design theme.

**Comment by mrgame64** [comment] 2015-08-03 01:09
Okay, now I was able to reproduce the issue. The theme doesn't seem to matter

**Comment by mrgame64** [comment] 2015-08-03 01:13
What versions of NodeBB are you all using, and did you have the same problem with a previous version?

**Comment by tfraley** [comment] 2015-08-03 01:14
I'm running 0.10.25

Works fine in chrome but doesn't want to work in safari

**Comment by mrgame64** [comment] 2015-08-03 01:21
I think that in such a critical case, the Redactor's support at Imperavi should be contacted, but only @drewdotpro who actually owns the license is able to do it, apparently.

**Comment by exomarty** [comment] 2015-08-04 07:57
doubt is a redactor issue because the editor works fine on his website demo on safari

**Comment by mrgame64** [comment] 2015-08-04 14:57
I've noticed that too, the problem must be within this plugin's implementation of Redactor

**Comment by tfraley** [comment] 2015-08-12 19:39
Just decided to test it again and still runing into the same issue. I would love to use redactor, but  currently can not. Any one have any suggestions?

**Comment by julianlam** [comment] 2015-08-12 19:49
Hey guys, what errors do you see in the web inspector?

**Comment by tfraley** [comment] 2015-08-12 19:53
@julianlam I just hit you up in chat on nodebb.. I just enabled reactor if you want to take a peek

**Comment by tfraley** [comment] 2015-08-12 19:57
@julianlam I don't see any errors that's what is strange. 
Safari 8.0.7 & also tested on my dev mashine running Safari 9.0 with same results

**Comment by tfraley** [comment] 2015-08-12 19:59
@julianlam also I will add if I go into HTML mode I can type fine

**Comment by drewdotpro** [comment] 2015-08-16 12:41
Without Safari or a Mac I can't look at this. Can anyone else?

**Comment by tfraley** [comment] 2015-08-16 14:44
@drewdotpro I don't know a ton about nodebb or the plugin's but I can lend a hand if you need something specific. I will be in the office 8am pst tomorrow hit me up any time after that

**Comment by segura2010** [comment] 2015-08-17 09:19
Fixed on my pull request https://github.com/NodeBB/nodebb-plugin-composer-redactor/pull/12

**Comment by drewdotpro** [comment] 2015-08-17 09:22
Thank you @segura2010

**Closed as completed** 2015-08-17 09:22 UTC
Labels: bug, help wanted
